### ISSUE TITLE
Methodlaştırma

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/hakan_peker_login_view#1]
Sayfa içerisindeki methodlaştırmaların güzel bu kısım da parçalanabilir
https://github.com/VBT-FlutterCamp/hakan_peker_login_view/blob/d2d58af7724af8729eccad6b45954200d50dc706/lib/feature/login/view/login_view.dart#L30

**Comment by hakannpeker** [comment]
burayı da düzelttim teşekkürler
